version: '0.4.0-{build}'

branches:
  only:
    - master
    - development
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

environment:
  auth_token:
    secure: rLuHhO0prerqoGCYmfOoyxqcwwamCXtuZtl4Jzqeu3aGgflk0mnX1fogLq68YcRW
  matrix:
    - prepare_mode: YES
      name: win32-prepare
      platform: amd64_x86
      qt: msvc2015
    - prepare_mode: NO
      name: win32
      platform: amd64_x86
      qt: msvc2015
    - prepare_mode: NO
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      name: win64
      platform: amd64
      qt: msvc2017_64
    - prepare_mode: NO
      name: win32
      platform: mingw
      qt: mingw492_32

clone_folder: c:\dev\libquentier

init:
  - if not %platform%==mingw set PATH=C:\Qt\5.9.2\%qt%\bin;%PATH%
  - if %platform%==mingw set PATH=C:\Qt\5.5\%qt%\bin;%PATH%
  - set ORIGPATH=%PATH%
  - if %qt%==msvc2017_64 set tool=VS2017_x64
  - if %qt%==msvc2015 set tool=VS2015_x86
  - if %qt%==mingw492_32 set tool=MinGW_x86
  - if %platform%==mingw set DEPLOYMENT_TARGET=libquentier-windows-qt55-%tool%.zip
  - if not %platform%==mingw set DEPLOYMENT_TARGET=libquentier-windows-qt592-%tool%.zip
  - if %platform%==amd64 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if %platform%==amd64_x86 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%
  - if not %platform%==mingw (set makefiles="NMake Makefiles") else (set makefiles="MinGW Makefiles")
  - if %platform%==mingw (set use_webkit=1) else (set use_webkit=0)
  - if %platform%==mingw set PATH=C:\MinGW\bin;C:\Program Files (x86)\CMake\bin;%PATH%
  - if not %name%==win64 set OPENSSL_ROOT_DIR=C:\OpenSSL-Win32 else set OPENSSL_ROOT_DIR=C:\OpenSSL-Win64
  - if not %qt%==msvc2017_64 set BOOST_ROOT=C:\Libraries\boost_1_63_0
  - if %qt%==msvc2017_64 set BOOST_ROOT=C:\Libraries\boost_1_65_1
  - if %qt%==msvc2017_64 set PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin";%PATH%
  - if %qt%==msvc2015 set PATH="C:\Program Files (x86)\MSBuild\14.0\Bin";%PATH%
  
install:
  - echo "Downloading ciuploadtool"
  - md c:\dev\ciuploadtool
  - cd c:\dev\ciuploadtool
  - curl -fsSL https://github.com/d1vanov/ciuploadtool/releases/download/continuous-master/ciuploadtool_windows_x86.zip -o ciuploadtool_windows_x86.zip
  - 7z x ciuploadtool_windows_x86.zip
  - if %prepare_mode%==YES c:\dev\ciuploadtool\ciuploadtool.exe -preponly -suffix="%APPVEYOR_REPO_BRANCH%"
  - ps: if ($env:prepare_mode -eq "YES") { throw "Failing in order to stop the current build matrix job early" }
# libiconv
  - echo "Downloading libiconv"
  - md c:\dev\libiconv
  - cd c:\dev\libiconv
  - if %qt%==msvc2015 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/libiconv-msvc2015_x86.zip -o libiconv-msvc2015_x86.zip
  - if %qt%==msvc2015 7z x libiconv-msvc2015_x86.zip
  - if %qt%==msvc2017_64 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/libiconv-msvc2017_x64.zip -o libiconv-msvc2017_x64.zip
  - if %qt%==msvc2017_64 7z x libiconv-msvc2017_x64.zip
  - if %qt%==mingw492_32 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/libiconv-mingw492_32_x86.zip -o libiconv-mingw492_32_x86.zip
  - if %qt%==mingw492_32 7z x libiconv-mingw492_32_x86.zip
  - set PATH=%cd%\bin;%PATH%
  - set LIB=%cd%\lib;%LIB%
  - set INCLUDE=%cd%\include;%INCLUDE%
# zlib
  - echo "Downloading zlib"
  - md c:\dev\zlib
  - cd c:\dev\zlib
  - if %qt%==msvc2015 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/zlib-msvc2015_x86.zip -o zlib-msvc2015_x86.zip
  - if %qt%==msvc2015 7z x zlib-msvc2015_x86.zip
  - if %qt%==msvc2017_64 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/zlib-msvc2017_x64.zip -o zlib-msvc2017_x64.zip
  - if %qt%==msvc2017_64 7z x zlib-msvc2017_x64.zip
  - if %qt%==mingw492_32 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/zlib-mingw492_32_x86.zip -o zlib-mingw492_32_x86.zip
  - if %qt%==mingw492_32 7z x zlib-mingw492_32_x86.zip
  - set PATH=%cd%\bin;%PATH%
  - set LIB=%cd%\lib;%LIB%
  - set INCLUDE=%cd%\include;%INCLUDE%
# libxml2
  - echo "Downloading libxml2"
  - md c:\dev\libxml2
  - cd c:\dev\libxml2
  - if %qt%==msvc2015 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/libxml2-msvc2015_x86.zip -o libxml2-msvc2015_x86.zip
  - if %qt%==msvc2015 7z x libxml2-msvc2015_x86.zip
  - if %qt%==msvc2017_64 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/libxml2-msvc2017_x64.zip -o libxml2-msvc2017_x64.zip
  - if %qt%==msvc2017_64 7z x libxml2-msvc2017_x64.zip
  - if %qt%==mingw492_32 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/libxml2-mingw492_32_x86.zip -o libxml2-mingw492_32_x86.zip
  - if %qt%==mingw492_32 7z x libxml2-mingw492_32_x86.zip
  - set PATH=%cd%\bin;%PATH%
  - set LIB=%cd%\lib;%LIB%
  - set INCLUDE=%cd%\include;%INCLUDE%
# libhunspell
  - echo "Downloading libhunspell"
  - md c:\dev\libhunspell
  - cd c:\dev\libhunspell
  - if %qt%==msvc2015 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/libhunspell-msvc2015_x86.zip -o libhunspell-msvc2015_x86.zip
  - if %qt%==msvc2015 7z x libhunspell-msvc2015_x86.zip
  - if %qt%==msvc2017_64 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/libhunspell-msvc2017_x64.zip -o libhunspell-msvc2017_x64.zip
  - if %qt%==msvc2017_64 7z x libhunspell-msvc2017_x64.zip
  - if %qt%==mingw492_32 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/libhunspell-mingw492_32_x86.zip -o libhunspell-mingw492_32_x86.zip
  - if %qt%==mingw492_32 7z x libhunspell-mingw492_32_x86.zip
  - set PATH=%cd%\bin;%PATH%
  - set LIB=%cd%\lib;%LIB%
  - set INCLUDE=%cd%\include;%INCLUDE%
# tidy-html5
  - echo "Downloading tidy-html5"
  - md c:\dev\tidy-html5
  - cd c:\dev\tidy-html5
  - if %qt%==msvc2015 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/tidy-html5-msvc2015_x86.zip -o tidy-html5-msvc2015_x86.zip
  - if %qt%==msvc2015 7z x tidy-html5-msvc2015_x86.zip
  - if %qt%==msvc2017_64 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/tidy-html5-msvc2017_x64.zip -o tidy-html5-msvc2017_x64.zip
  - if %qt%==msvc2017_64 7z x tidy-html5-msvc2017_x64.zip
  - if %qt%==mingw492_32 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/tidy-html5-mingw492_32_x86.zip -o tidy-html5-mingw492_32_x86.zip
  - if %qt%==mingw492_32 7z x tidy-html5-mingw492_32_x86.zip
  - set PATH=%cd%\bin;%PATH%
  - set LIB=%cd%\lib;%LIB%
  - set INCLUDE=%cd%\include;%INCLUDE%
# Qtkeychain
  - echo "Downloading qtkeychain"
  - md c:\dev\qtkeychain
  - cd c:\dev\qtkeychain
  - if %qt%==msvc2015 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/qtkeychain-msvc2015_x86.zip -o qtkeychain-msvc2015_x86.zip
  - if %qt%==msvc2015 7z x qtkeychain-msvc2015_x86.zip
  - if %qt%==msvc2017_64 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/qtkeychain-msvc2017_x64.zip -o qtkeychain-msvc2017_x64.zip
  - if %qt%==msvc2017_64 7z x qtkeychain-msvc2017_x64.zip
  - if %qt%==mingw492_32 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/releases/download/continuous/qtkeychain-mingw492_32_x86.zip -o qtkeychain-mingw492_32_x86.zip
  - if %qt%==mingw492_32 7z x qtkeychain-mingw492_32_x86.zip
  - set PATH=%cd%\bin;%PATH%
  - set LIB=%cd%\lib;%LIB%
  - set INCLUDE=%cd%\include;%INCLUDE%
# QEverCloud
  - echo "Downloading QEverCloud"
  - md c:\dev\qevercloud
  - cd c:\dev\qevercloud
# First try to download the prebuilt binary to save the precious time as well as CPU cycles
  - md build\installdir
  - cd build\installdir
  - set QEVERCLOUD_DOWNLOADED=0
  - if %qt%==msvc2015 if %APPVEYOR_REPO_BRANCH%=="development" curl -fsSL https://github.com/d1vanov/QEverCloud/releases/download/continuous-development/qevercloud-windows-qt592-VS2015_x86.zip -o qevercloud-windows-qt592-VS2015_x86.zip & set errorlevel=0
  - if %qt%==msvc2015 if not %APPVEYOR_REPO_BRANCH%=="development" curl -fsSL https://github.com/d1vanov/QEverCloud/releases/download/continuous-master/qevercloud-windows-qt592-VS2015_x86.zip -o qevercloud-windows-qt592-VS2015_x86.zip & set errorlevel=0
  - if %qt%==msvc2017_64 if %APPVEYOR_REPO_BRANCH%=="development" curl -fsSL https://github.com/d1vanov/QEverCloud/releases/download/continuous-development/qevercloud-windows-qt592-VS2017_x64.zip -o qevercloud-windows-qt592-VS2017_x64.zip & set errorlevel=0
  - if %qt%==msvc2017_64 if not %APPVEYOR_REPO_BRANCH%=="development" curl -fsSL https://github.com/d1vanov/QEverCloud/releases/download/continuous-master/qevercloud-windows-qt592-VS2017_x64.zip -o qevercloud-windows-qt592-VS2017_x64.zip & set errorlevel=0
  - if %qt%==mingw492_32 if %APPVEYOR_REPO_BRANCH%=="development" curl -fsSL https://github.com/d1vanov/QEverCloud/releases/download/continuous-development/qevercloud-windows-qt55-MinGW_x86.zip -o qevercloud-windows-qt55-MinGW_x86.zip & set errorlevel=0
  - if %qt%==mingw492_32 if not %APPVEYOR_REPO_BRANCH%=="development" curl -fsSL https://github.com/d1vanov/QEverCloud/releases/download/continuous-master/qevercloud-windows-qt55-MinGW_x86.zip -o qevercloud-windows-qt55-MinGW_x86.zip & set errorlevel=0
  - if %qt%==msvc2015 if exist qevercloud-windows-qt592-VS2015_x86.zip set QEVERCLOUD_DOWNLOADED=1
  - if %qt%==msvc2017_64 if exist qevercloud-windows-qt592-VS2017_x64.zip set QEVERCLOUD_DOWNLOADED=1
  - if %qt%==mingw492_32 if exist qevercloud-windows-qt55-MinGW_x86.zip set QEVERCLOUD_DOWNLOADED=1
  - if %qt%==msvc2015 if %QEVERCLOUD_DOWNLOADED%==1 7z x qevercloud-windows-qt592-VS2015_x86.zip
  - if %qt%==msvc2017_64 if %QEVERCLOUD_DOWNLOADED%==1 7z x qevercloud-windows-qt592-VS2017_x64.zip
  - if %qt%==mingw492_32 if %QEVERCLOUD_DOWNLOADED%==1 7z x qevercloud-windows-qt55-MinGW_x86.zip
  - if %QEVERCLOUD_DOWNLOADED%==1 set PATH=%cd%\bin;%PATH%
  - if %QEVERCLOUD_DOWNLOADED%==1 set LIB=%cd%\lib;%LIB%
  - if %QEVERCLOUD_DOWNLOADED%==1 set INCLUDE=%cd%\lib;%INCLUDE%
# In case of failure clone the QEverCloud repo and build the library from sources
  - if not %QEVERCLOUD_DOWNLOADED%==1 cd c:\dev
  - if not %QEVERCLOUD_DOWNLOADED%==1 git clone https://github.com/d1vanov/QEverCloud.git qevercloud
  - if not %QEVERCLOUD_DOWNLOADED%==1 cd c:\dev\qevercloud
  - if not %QEVERCLOUD_DOWNLOADED%==1 echo "Building QEverCloud"
  - if not %QEVERCLOUD_DOWNLOADED%==1 if %APPVEYOR_REPO_BRANCH%=="development" git checkout development
  - if not %QEVERCLOUD_DOWNLOADED%==1 cd build
  - if not %QEVERCLOUD_DOWNLOADED%==1 if %qt%==mingw492_32 set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if not %QEVERCLOUD_DOWNLOADED%==1 if %qt%==mingw492_32 set PATH=C:\MinGW\bin;C:\Qt\5.5\%qt%\bin;%PATH%
  - if not %QEVERCLOUD_DOWNLOADED%==1 if not %qt%==mingw492_32 cmake .. -G %makefiles% -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="c:\dev\qevercloud\build\installdir" -DUSE_QT5=1 -DCMAKE_PREFIX_PATH="C:/Qt/5.9.2/%qt%
  - if not %QEVERCLOUD_DOWNLOADED%==1 if %qt%==mingw492_32 cmake .. -G %makefiles% -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="c:\dev\qevercloud\build\installdir" -DUSE_QT5=1 -DUSE_QT5_WEBKIT=1 -DCMAKE_PREFIX_PATH="C:/Qt/5.5/%qt%
  - if not %QEVERCLOUD_DOWNLOADED%==1 cmake --build . --target all
  - if not %QEVERCLOUD_DOWNLOADED%==1 cmake --build . --target check
  - if not %QEVERCLOUD_DOWNLOADED%==1 cmake --build . --target install
  - if not %QEVERCLOUD_DOWNLOADED%==1 if %qt%==mingw492_32 set PATH=%PATH%;C:\Program Files\Git\usr\bin
  - if not %QEVERCLOUD_DOWNLOADED%==1 set PATH=%PATH%;%cd%\installdir\bin
  - if not %QEVERCLOUD_DOWNLOADED%==1 set LIB=%LIB%;%cd%\installdir\lib
  - if not %QEVERCLOUD_DOWNLOADED%==1 set INCLUDE=%INCLUDE%;%cd%\installdir\include
  - cd c:\dev

before_build:
  - cd c:\dev\libquentier
  - md build

build_script:
  - cd c:\dev\libquentier\build
  - if %qt%==mingw492_32 set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if %qt%==mingw492_32 set PATH=C:\MinGW\bin;C:\Qt\5.5\%qt%\bin;%PATH%
  - if not %qt%==mingw492_32 C:\msys64\usr\bin\bash -lc "cd /c/dev/libquentier && echo 'install(FILES $<TARGET_PDB_FILE:${LIBNAME}> DESTINATION bin OPTIONAL)' >> CMakeLists.txt"
  - if %qt%==mingw492_32 cmake .. -G %makefiles% -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="c:/dev/libquentier/build/installdir" -DUSE_QT5=1 -DUSE_QT5_WEBKIT=1 -DCMAKE_PREFIX_PATH="C:/Qt/5.5/%qt%"
  - if not %qt%==mingw492_32 cmake .. -G %makefiles% -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="c:/dev/libquentier/build/installdir" -DUSE_QT5=1 -DCMAKE_PREFIX_PATH="C:/Qt/5.9.2/%qt%"
  - cmake --build . --target all
  - cmake --build . --target check
  - cmake --build . --target install
  - if %qt%==mingw492_32 set PATH=%ORIGPATH%

after_build:
  - cd c:\dev\libquentier\build\installdir
  - 7z a %DEPLOYMENT_TARGET% *
  - cp %DEPLOYMENT_TARGET% %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  - c:\dev\ciuploadtool\ciuploadtool.exe -suffix="%APPVEYOR_REPO_BRANCH%" %DEPLOYMENT_TARGET%

artifacts:
  - path: '*.zip'
    name: archive

matrix:
  fast_finish: true
  allow_failures:
    - prepare_mode: YES
