version: '0.4.0-{build}'

branches:
  only:
    - master
    - development
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

environment:
  auth_token:
    secure: upe+zH95QfXvoMZJdhk37+Z0Wp8+vDpMmrrrxQDdBLL3mn4Yvm8/g6M/WElgOhN3
  matrix:
    - prepare_mode: YES
      name: win32-prepare
      platform: amd64_x86
      qt: msvc2015
    - prepare_mode: NO
      name: win32
      platform: amd64_x86
      qt: msvc2015
    - prepare_mode: NO
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      name: win64
      platform: amd64
      qt: msvc2017_64
    - prepare_mode: NO
      name: win32
      platform: mingw
      qt: mingw492_32

clone_folder: c:\dev\libquentier

init:
  - if not %platform%==mingw set PATH=C:\Qt\5.9.2\%qt%\bin;%PATH%
  - if %platform%==mingw set PATH=C:\Qt\5.5\%qt%\bin;%PATH%
  - set ORIGPATH=%PATH%
  - if %platform%==amd64 set tool=VS2017_x64
  - if %platform%==amd64_x86 set tool=VS2015_x86
  - if %platform%==mingw492_32 set tool=MinGW_x86
  - if %platform%==mingw set DEPLOYMENT_TARGET=libquentier-windows-qt55-%tool%-%APPVEYOR_REPO_COMMIT:~0,7%.zip
  - if not %platform%==mingw set DEPLOYMENT_TARGET=libquentier-windows-qt592-%tool%-%APPVEYOR_REPO_COMMIT:~0,7%.zip
  - if %platform%==amd64 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if %platform%==amd64_x86 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%
  - if not %platform%==mingw (set makefiles="NMake Makefiles") else (set makefiles="MinGW Makefiles")
  - if %platform%==mingw (set use_webkit=1) else (set use_webkit=0)
  - if %platform%==mingw set PATH=C:\MinGW\bin;C:\Program Files (x86)\CMake\bin;%PATH%
  - if not %name%==win64 set OPENSSL_ROOT_DIR=C:\OpenSSL-Win32 else set OPENSSL_ROOT_DIR=C:\OpenSSL-Win64
  - if not %qt%==msvc2017_64 set BOOST_ROOT=C:\Libraries\boost_1_63_0
  - if %qt%==msvc2017_64 set BOOST_ROOT=C:\Libraries\boost_1_65_1
  - if %qt%==msvc2017_64 set PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin";%PATH%
  - if %qt%==msvc2015 set PATH="C:\Program Files (x86)\MSBuild\14.0\Bin";%PATH%
  
install:
  - echo "Downloading ciuploadtool"
  - md c:\dev\ciuploadtool
  - cd c:\dev\ciuploadtool
  - curl -fsSL https://github.com/d1vanov/ciuploadtool/releases/download/continuous-master/ciuploadtool_windows_x86.zip -o ciuploadtool_windows_x86.zip
  - 7z x ciuploadtool_windows_x86.zip
  - if %prepare_mode%==YES c:\dev\ciuploadtool\ciuploadtool.exe -preponly -suffix="%APPVEYOR_REPO_BRANCH%"
  - ps: if ($env:prepare_mode -eq "YES") { throw "Failing in order to stop the current build matrix job early" }
  - echo "Downloading libiconv"
  - md c:\dev\libiconv
  - cd c:\dev\libiconv
  - if %qt%==msvc2015 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/msvc/VS2015_x86/libiconv-msvc2015-x86.7z -o libiconv-msvc2015-x86.7z
  - if %qt%==msvc2015 7z x libiconv-msvc2015-x86.7z
  - if %qt%==msvc2017_64 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/msvc/VS2017_x64/libiconv-msvc2017-x64.7z -o libiconv-msvc2017-x64.7z
  - if %qt%==msvc2017_64 7z x libiconv-msvc2017-x64.7z
  - if %qt%==mingw492_32 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/mingw/mingw32/libiconv-mingw-x86.7z -o libiconv-mingw-x86.7z
  - if %qt%==mingw492_32 7z x libiconv-mingw-x86.7z
  - set PATH=%cd%\bin;%PATH%
  - set LIB=%cd%\lib;%LIB%
  - set INCLUDE=%cd%\include;%INCLUDE%
  - echo "Downloading zlib"
  - md c:\dev\zlib
  - cd c:\dev\zlib
  - if %qt%==msvc2015 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/msvc/VS2015_x86/zlib-msvc2015-x86.7z -o zlib-msvc2015-x86.7z
  - if %qt%==msvc2015 7z x zlib-msvc2015-x86.7z
  - if %qt%==msvc2017_64 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/msvc/VS2017_x64/zlib-msvc2017-x64.7z -o zlib-msvc2017-x64.7z
  - if %qt%==msvc2017_64 7z x zlib-msvc2017-x64.7z
  - if %qt%==mingw492_32 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/mingw/mingw32/zlib-mingw-x86.7z -o zlib-mingw-x86.7z
  - if %qt%==mingw492_32 7z x zlib-mingw-x86.7z
  - set PATH=%cd%\bin;%PATH%
  - set LIB=%cd%\lib;%LIB%
  - set INCLUDE=%cd%\include;%INCLUDE%
  - echo "Downloading libxml2"
  - md c:\dev\libxml2
  - cd c:\dev\libxml2
  - if %qt%==msvc2015 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/msvc/VS2015_x86/libxml2-msvc2015-x86.7z -o libxml2-msvc2015-x86.7z
  - if %qt%==msvc2015 7z x libxml2-msvc2015-x86.7z
  - if %qt%==msvc2017_64 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/msvc/VS2017_x64/libxml2-msvc2017-x64.7z -o libxml2-msvc2017-x64.7z
  - if %qt%==msvc2017_64 7z x libxml2-msvc2017-x64.7z
  - if %qt%==mingw492_32 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/mingw/mingw32/libxml2-mingw-x86.7z -o libxml2-mingw-x86.7z
  - if %qt%==mingw492_32 7z x libxml2-mingw-x86.7z
  - set PATH=%cd%\bin;%PATH%
  - set LIB=%cd%\lib;%LIB%
  - set INCLUDE=%cd%\include;%INCLUDE%
  - echo "Downloading libhunspell"
  - md c:\dev\libhunspell
  - cd c:\dev\libhunspell
  - if %qt%==msvc2015 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/msvc/VS2015_x86/libhunspell-msvc2015-x86.7z -o libhunspell-msvc2015-x86.7z
  - if %qt%==msvc2015 7z x libhunspell-msvc2015-x86.7z
  - if %qt%==msvc2017_64 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/msvc/VS2017_x64/libhunspell-msvc2017-x64.7z -o libhunspell-msvc2017-x64.7z
  - if %qt%==msvc2017_64 7z x libhunspell-msvc2017-x64.7z
  - if %qt%==mingw492_32 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/mingw/mingw32/libhunspell-mingw-x86.7z -o libhunspell-mingw-x86.7z
  - if %qt%==mingw492_32 7z x libhunspell-mingw-x86.7z
  - set PATH=%cd%\bin;%PATH%
  - set LIB=%cd%\lib;%LIB%
  - set INCLUDE=%cd%\include;%INCLUDE%
  - echo "Downloading tidy-html5"
  - md c:\dev\tidy-html5
  - cd c:\dev\tidy-html5
  - if %qt%==msvc2015 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/msvc/VS2015_x86/tidy-html5-msvc2015-x86.7z -o tidy-html5-msvc2015-x86.7z
  - if %qt%==msvc2015 7z x tidy-html5-msvc2015-x86.7z
  - if %qt%==msvc2017_64 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/msvc/VS2017_x64/tidy-html5-msvc2017-x64.7z -o tidy-html5-msvc2017-x64.7z
  - if %qt%==msvc2017_64 7z x tidy-html5-msvc2017-x64.7z
  - if %qt%==mingw492_32 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/mingw/mingw32/tidy-html5-mingw-x86.7z -o tidy-html5-mingw-x86.7z
  - if %qt%==mingw492_32 7z x tidy-html5-mingw-x86.7z
  - set PATH=%cd%\bin;%PATH%
  - set LIB=%cd%\lib;%LIB%
  - set INCLUDE=%cd%\include;%INCLUDE%
  - echo "Downloading qtkeychain"
  - md c:\dev\qtkeychain
  - cd c:\dev\qtkeychain
  - if %qt%==msvc2015 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/msvc/VS2015_x86/qtkeychain-msvc2015-x86.7z -o qtkeychain-msvc2015-x86.7z
  - if %qt%==msvc2015 7z x qtkeychain-msvc2015-x86.7z
  - if %qt%==msvc2017_64 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/msvc/VS2017_x64/qtkeychain-msvc2017-x64.7z -o qtkeychain-msvc2017-x64.7z
  - if %qt%==msvc2017_64 7z x qtkeychain-msvc2017-x64.7z
  - if %qt%==mingw492_32 curl -fsSL https://github.com/d1vanov/quentier-dependencies-windows/raw/master/mingw/mingw32/qtkeychain-mingw-x86.7z -o qtkeychain-mingw-x86.7z
  - if %qt%==mingw492_32 7z x qtkeychain-mingw-x86.7z
  - set PATH=%cd%\bin;%PATH%
  - set LIB=%cd%\lib;%LIB%
  - set INCLUDE=%cd%\include;%INCLUDE%
  - echo "Downloading QEverCloud"
  - md c:\dev\qevercloud
  - cd c:\dev
  - git clone https://github.com/d1vanov/QEverCloud.git qevercloud
  - echo "Building QEverCloud"
  - cd c:\dev\qevercloud
  - if %APPVEYOR_REPO_BRANCH%=="development" git checkout development
  - md build
  - cd build
  - if %qt%==mingw492_32 set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if %qt%==mingw492_32 set PATH=C:\MinGW\bin;C:\Qt\5.5\%qt%\bin;%PATH%
  - if not %qt%==mingw492_32 cmake .. -G %makefiles% -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="c:\dev\qevercloud\build\installdir" -DUSE_QT5=1 -DCMAKE_PREFIX_PATH="C:/Qt/5.9.2/%qt%
  - if %qt%==mingw492_32 cmake .. -G %makefiles% -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="c:\dev\qevercloud\build\installdir" -DUSE_QT5=1 -DUSE_QT5_WEBKIT=1 -DCMAKE_PREFIX_PATH="C:/Qt/5.5/%qt%
  - cmake --build . --target all
  - cmake --build . --target check
  - cmake --build . --target install
  - if %qt%==mingw492_32 set PATH=%PATH%;C:\Program Files\Git\usr\bin
  - set PATH=%PATH%;%cd%\installdir\bin
  - set LIB=%LIB%;%cd%\installdir\lib
  - set INCLUDE=%INCLUDE%;%cd%\installdir\include
  - cd c:\dev

before_build:
  - cd c:\dev\libquentier
  - md build

build_script:
  - cd c:\dev\libquentier\build
  - if %qt%==mingw492_32 set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if %qt%==mingw492_32 set PATH=C:\MinGW\bin;C:\Qt\5.5\%qt%\bin;%PATH%
  - if not %qt%==mingw492_32 C:\msys64\usr\bin\bash -lc "cd /c/dev/libquentier && echo 'install(FILES $<TARGET_PDB_FILE:${LIBNAME}> DESTINATION bin OPTIONAL)' >> CMakeLists.txt"
  - if %qt%==mingw492_32 cmake .. -G %makefiles% -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="c:/dev/install" -DUSE_QT5=1 -DUSE_QT5_WEBKIT=1 -DCMAKE_PREFIX_PATH="C:/Qt/5.5/%qt%"
  - if not %qt%==mingw492_32 cmake .. -G %makefiles% -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="c:/dev/install" -DUSE_QT5=1 -DCMAKE_PREFIX_PATH="C:/Qt/5.9.2/%qt%"
  - cmake --build . --target all
  - cmake --build . --target check
  - cmake --build . --target install
  - if %qt%==mingw492_32 set PATH=%ORIGPATH%

after_build:
  - cd c:\dev\install
  - 7z a %DEPLOYMENT_TARGET% c:\dev\install\*
  - cp %DEPLOYMENT_TARGET% %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  - c:\dev\ciuploadtool\ciuploadtool.exe -suffix="%APPVEYOR_REPO_BRANCH%" %DEPLOYMENT_TARGET%

artifacts:
  - path: '*.zip'
    name: archive

matrix:
  fast_finish: true
  allow_failures:
    - prepare_mode: YES
