find_package(Qt5Keychain QUIET REQUIRED)

include_directories(SYSTEM ${QTKEYCHAIN_INCLUDE_DIRS})

get_property(QTKEYCHAIN_LIBRARY_LOCATION TARGET ${QTKEYCHAIN_LIBRARIES} PROPERTY LOCATION)
message(STATUS "Found QtKeychain library: ${QTKEYCHAIN_LIBRARY_LOCATION}")

if(NOT TARGET Qt5Keychain::Qt5Keychain)
  add_library(Qt5Keychain::Qt5Keychain UNKNOWN IMPORTED)
  set_target_properties(Qt5Keychain::Qt5Keychain PROPERTIES
    IMPORTED_LOCATION "${QTKEYCHAIN_LIBRARIES}"
    INTERFACE_INCLUDE_DIRECTORIES "${QTKEYCHAIN_INCLUDE_DIRS}")
endif()
